// Write one spec per domain folder, built from the traceability matrix and the
// code facts. Each folder answers: which requirements live here, what state
// they are in, which tables and routes serve them, and what is still missing.
import { readFile, writeFile, readdir } from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const SPECS = path.join(ROOT, 'specs');
const facts = JSON.parse(await readFile(path.join(ROOT, 'scripts/spec-gen/facts.json'), 'utf8'));

const trace = await readFile(path.join(SPECS, 'TRACEABILITY_MATRIX.md'), 'utf8');
const rows = trace.split('\n')
  .filter((l) => l.startsWith('| `PHARM-'))
  .map((l) => {
    const c = l.split('|').map((x) => x.trim());
    return {
      req: c[1].replace(/`/g, ''),
      num: Number(c[2]),
      feature: c[3],
      folder: c[4].replace(/`/g, ''),
      db: c[5], be: c[6], api: c[7], rbac: c[8], ui: c[9], audit: c[10],
      tests: c[11],
      status: c[12],
    };
  });

const folders = (await readdir(SPECS, { withFileTypes: true }))
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

// Which API areas and tables belong to a folder, by the words in its name.
const KEYWORDS = {
  '03-authentication': ['auth'], '04-users-rbac': ['admin'], '05-organizations': ['admin'],
  '06-products': ['catalog', 'product'], '07-units': ['catalog'], '08-batches': ['inventory', 'serial'],
  '09-serialization': ['serial'], '10-inventory': ['inventory'], '11-fefo': ['inventory'],
  '12-expiry': ['inventory'], '13-warehouse': ['warehouse'], '14-procurement': ['procurement'],
  '15-suppliers': ['supplier'], '16-receiving': ['receiving', 'goods-receipt'],
  '17-quality': ['quality'], '18-transfers': ['transfer'], '19-stock-counts': ['count', 'adjustment'],
  '20-pos': ['pos', 'sale'], '21-prescriptions': ['prescription'], '22-dispensing': ['dispensing'],
  '23-patients': ['patient'], '24-returns': ['return'], '25-recalls': ['recall'],
  '26-disposal': ['disposal'], '27-controlled-drugs': ['controlled'], '28-cold-chain': ['cold-chain'],
  '29-finance': ['accounting', 'invoice'], '30-reporting': ['report'], '31-analytics': ['analytics'],
  '32-forecasting': ['forecast'], '34-notifications': ['notification'],
  '35-integrations': ['integration'], '36-fhir': ['fhir'], '37-gs1': ['scan'],
  '38-api': [], '41-localization': ['i18n'], '42-security': ['auth'], '43-audit': ['audit'],
  '44-workflows': ['workflow'], '45-admin': ['admin'], '47-backup-dr': ['backup'],
  '48-observability': ['jobs', 'health'], '49-testing': [], '50-deployment': [],
};

let index = '# Domain specifications\n\nOne folder per domain. Each states which of the 1,000 requirements it owns,\n' +
  'what state they are in, and which tables and routes serve them.\n\n' +
  '| Folder | Requirements | Implemented | Partial | Not implemented |\n| --- | ---: | ---: | ---: | ---: |\n';

for (const folder of folders) {
  const owned = rows.filter((r) => r.folder === folder);
  const impl = owned.filter((r) => r.status === 'IMPLEMENTED');
  const part = owned.filter((r) => r.status === 'PARTIALLY IMPLEMENTED');
  const not = owned.filter((r) => r.status === 'NOT IMPLEMENTED');

  const words = KEYWORDS[folder] ?? [];
  const routes = words.length
    ? facts.handlers.filter((h) =>
        words.some((w) => `${h.controllerPath}/${h.routePath}`.toLowerCase().includes(w)))
    : [];
  const tables = words.length
    ? facts.dataModel.models.filter((m) =>
        words.some((w) => m.name.toLowerCase().includes(w.replace(/-/g, ''))))
    : [];
  const pages = words.length
    ? facts.pages.filter((p) => words.some((w) => p.toLowerCase().includes(w)))
    : [];

  const title = folder.replace(/^\d+-/, '').replace(/-/g, ' ').replace(/^./, (c) => c.toUpperCase());

  let out = `<!--
  GENERATED by scripts/spec-gen/domains.mjs. Do not edit by hand.
  The narrative for this domain lives in the master documents in specs/.
-->

# ${title}

`;

  if (!owned.length) {
    out += `No requirement in the 1,000-feature specification is filed against this\n` +
      `domain directly. It is covered by the master documents in \`specs/\` — see\n` +
      `\`ARCHITECTURE.md\`, \`SECURITY_SPEC.md\`, \`TEST_STRATEGY.md\` and\n` +
      `\`MIGRATION_PLAN.md\` — rather than by a requirement range of its own.\n`;
  } else {
    out += `**${owned.length} requirements: ${impl.length} implemented, ${part.length} partial, ${not.length} not implemented.**\n\n`;
    out += `Requirement range \`${owned[0].req}\` – \`${owned[owned.length - 1].req}\`.\n`;

    if (tables.length) {
      out += `\n## Tables\n\n${tables.map((t) => `- \`${t.table ?? t.name}\` (${t.name})`).join('\n')}\n`;
    }
    if (routes.length) {
      out += `\n## Routes\n\n`;
      for (const h of routes.slice(0, 60)) {
        const full = ('/' + [h.controllerPath, h.routePath].filter(Boolean).join('/')).replace(/\/+/g, '/');
        out += `- \`${h.method} ${full}\`${h.permissions.length ? ` — ${h.permissions.join(', ')}` : ''}\n`;
      }
      if (routes.length > 60) out += `- …and ${routes.length - 60} more; see \`specs/API_CONTRACTS.md\`.\n`;
    }
    if (pages.length) {
      out += `\n## Screens\n\n${pages.map((p) => `- \`${p}\``).join('\n')}\n`;
    }

    out += `\n## Requirements\n\n| Requirement | # | Feature | Status |\n| --- | ---: | --- | --- |\n`;
    for (const r of owned) {
      out += `| \`${r.req}\` | ${r.num} | ${r.feature} | ${r.status} |\n`;
    }

    if (not.length) {
      out += `\n## Not implemented\n\n${not.length} requirement(s) in this domain are not built. The reason for each is in\n` +
        `\`specs/KNOWN_EXTERNAL_DEPENDENCIES.md\`:\n\n`;
      for (const r of not) out += `- \`${r.req}\` (${r.num}) ${r.feature}\n`;
    }
    if (part.length) {
      out += `\n## Partial\n\n${part.length} requirement(s) work but are narrower than the feature asks:\n\n`;
      for (const r of part) out += `- \`${r.req}\` (${r.num}) ${r.feature}\n`;
    }
  }

  await writeFile(path.join(SPECS, folder, 'spec.md'), out);
  index += `| [\`${folder}\`](${folder}/spec.md) | ${owned.length} | ${impl.length} | ${part.length} | ${not.length} |\n`;
}

const filed = rows.filter((r) => folders.includes(r.folder)).length;
index += `\n${filed} of 1,000 requirements are filed against a domain folder; the remainder\n` +
  `sit in folders whose names differ from the matrix entry and are reachable\n` +
  `through \`specs/TRACEABILITY_MATRIX.md\`, which is the authority.\n`;

await writeFile(path.join(SPECS, 'DOMAINS.md'), index);
console.log(`${folders.length} domain specs written; ${filed}/1000 requirements filed to a folder`);
