// Write the specification documents that are derived from code, so they cannot
// drift from it. Anything that is a judgement rather than a fact — why the
// architecture is shaped this way, what the security posture is — is written by
// hand and lives in its own file; this only generates what the code can prove.
//
//   node scripts/spec-gen/extract.mjs && node scripts/spec-gen/generate.mjs
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const facts = JSON.parse(await readFile(path.join(ROOT, 'scripts/spec-gen/facts.json'), 'utf8'));
const SPECS = path.join(ROOT, 'specs');

const HEADER = (title, note) => `<!--
  GENERATED by scripts/spec-gen/generate.mjs from the code itself.
  Do not edit by hand: run \`node scripts/spec-gen/extract.mjs && node scripts/spec-gen/generate.mjs\`.
-->

# ${title}

${note}

Generated ${new Date().toISOString().slice(0, 10)} from the schema, the route table and the permission catalogue.
`;

// ============================================================
// DATA_MODEL.md
// ============================================================
{
  const { models, enums } = facts.dataModel;

  // Group by the part of the system a model belongs to, so a reader looking for
  // "how is a batch stored" is not scrolling through 114 alphabetical models.
  const GROUPS = [
    ['Identity and access', /^(User|Role|Permission|UserRole|RolePermission|UserScope|Session|ApiKey|PasswordReset)/],
    ['Organisation', /^(Company|BusinessUnit|Region|Branch|Department|Warehouse|WarehouseLocation)/],
    ['Drug master', /^(Product|Category|Manufacturer|Ingredient|Unit|Barcode|ProductCategory|ProductBarcode|ProductUnit|ProductIngredient|ProductRelation|ProductAttribute)/],
    ['Stock', /^(Batch|Serial|Inventory|Stock|Reservation|CostLayer|CostConsumption)/],
    ['Procurement', /^(Supplier|Purchase|Rfq|Quotation|GoodsReceipt)/],
    ['Sales and dispensing', /^(Sale|Payment|CashSession|Prescription|Dispensing|Patient|Customer|LoyaltyLedger)/],
    ['Quality and compliance', /^(Quality|Recall|Return|Disposal|Damage|Quarantine|Temperature|Sensor|ControlledRegister)/],
    ['Finance', /^(Account|Journal|SupplierInvoice|FinanceNote|Valuation|Tax)/],
    ['Platform', /^(Setting|FeatureFlag|AuditLog|Notification|Automation|Workflow|Job|Import|Document|Integration|Webhook|SavedReport|Backup|Translation)/],
  ];

  const grouped = new Map(GROUPS.map(([name]) => [name, []]));
  grouped.set('Other', []);
  for (const m of models) {
    const hit = GROUPS.find(([, re]) => re.test(m.name));
    grouped.get(hit ? hit[0] : 'Other').push(m);
  }

  let out = HEADER(
    'Data model',
    'Every table, what it is for, and the fields that carry meaning rather than plumbing.\n\n' +
    'Money and quantities are `Decimal`, never float: a pharmacy that rounds a\n' +
    'unit price in binary floating point will disagree with its own invoices.\n' +
    'Primary keys are UUIDs so a record can be created in one branch and\n' +
    'referenced in another without a central sequence.',
  );

  out += `\n**${models.length} tables, ${enums.length} enumerations.**\n`;

  for (const [group, list] of grouped) {
    if (!list.length) continue;
    out += `\n## ${group}\n\n`;
    for (const m of list.sort((a, b) => a.name.localeCompare(b.name))) {
      out += `### ${m.name}${m.table ? ` — \`${m.table}\`` : ''}\n\n`;
      if (m.doc) out += `${m.doc}\n\n`;
      const meaningful = m.fields.filter(
        (f) => !['id', 'createdAt', 'updatedAt'].includes(f.name) && !f.relation,
      );
      if (meaningful.length) {
        out += '| Field | Type | Notes |\n| --- | --- | --- |\n';
        for (const f of meaningful) {
          const notes = [
            f.doc,
            /@unique/.test(f.attributes) ? 'unique' : '',
            /@default/.test(f.attributes) ? `default ${/@default\(([^)]*)\)/.exec(f.attributes)?.[1]}` : '',
          ].filter(Boolean).join('; ');
          out += `| \`${f.name}\` | ${f.type} | ${notes.replace(/\|/g, '\\|')} |\n`;
        }
      }
      const rels = m.fields.filter((f) => f.relation);
      if (rels.length) {
        out += `\nRelations: ${rels.map((r) => `\`${r.name}\` → ${r.type.replace(/[?[\]]/g, '')}`).join(', ')}\n`;
      }
      if (m.indexes.length) {
        out += `\nIndexes and constraints: ${m.indexes.map((i) => `\`${i}\``).join(', ')}\n`;
      }
      out += '\n';
    }
  }

  out += '\n## Enumerations\n\n';
  for (const e of enums.sort((a, b) => a.name.localeCompare(b.name))) {
    out += `- **${e.name}**: ${e.values.map((v) => `\`${v}\``).join(', ')}\n`;
  }

  await writeFile(path.join(SPECS, 'DATA_MODEL.md'), out);
  console.log('DATA_MODEL.md');
}

// ============================================================
// API_CONTRACTS.md
// ============================================================
{
  const byTag = new Map();
  for (const h of facts.handlers) {
    const key = h.tag ?? h.module;
    if (!byTag.has(key)) byTag.set(key, []);
    const full = ('/' + [h.controllerPath, h.routePath].filter(Boolean).join('/')).replace(/\/+/g, '/');
    byTag.get(key).push({ ...h, full });
  }

  const unguarded = facts.handlers.filter((h) => !h.permissions.length && !h.isPublic);

  let out = HEADER(
    'API contracts',
    'Every route the application serves, the permissions it requires, and what it is for.\n\n' +
    'Authorization is declared on the handler and enforced by a guard before the\n' +
    'handler runs. A route with no `@RequirePermissions` and no `@Public` is a\n' +
    'route nobody decided about, so they are listed separately below rather than\n' +
    'buried in the table.',
  );

  out += `\n**${facts.routes.length} routes across ${byTag.size} areas.**\n\n`;
  out += 'Every route is served twice: unversioned under `/api`, and under `/api/v1`.\n';
  out += 'A client that has been calling `/api/...` keeps working; a new integration\n';
  out += 'can pin `/api/v1/...`. A future `v2` is added per controller with\n';
  out += '`@Version(\'2\')`, and `v1` stays as it is until it is deliberately retired.\n';

  for (const [tag, list] of [...byTag.entries()].sort()) {
    out += `\n## ${tag}\n\n`;
    out += '| Method | Path | Requires | Purpose |\n| --- | --- | --- | --- |\n';
    for (const h of list.sort((a, b) => a.full.localeCompare(b.full))) {
      const guard = h.isPublic
        ? '_public_'
        : h.permissions.length
          ? h.permissions.map((p) => `\`${p}\``).join(' + ')
          : '**authenticated only**';
      out += `| ${h.method} | \`${h.full}\` | ${guard} | ${(h.summary ?? '').replace(/\|/g, '\\|')} |\n`;
    }
  }

  out += '\n## Routes with no declared permission\n\n';
  if (!unguarded.length) {
    out += 'None. Every route either declares the permissions it needs or is explicitly public.\n';
  } else {
    out += `${unguarded.length} route(s) require authentication but declare no permission. Each is\n`;
    out += 'listed so the choice is visible rather than accidental:\n\n';
    for (const h of unguarded) {
      const full = ('/' + [h.controllerPath, h.routePath].filter(Boolean).join('/')).replace(/\/+/g, '/');
      out += `- \`${h.method} ${full}\` (${h.module})\n`;
    }
  }

  await writeFile(path.join(SPECS, 'API_CONTRACTS.md'), out);
  console.log(`API_CONTRACTS.md (${unguarded.length} unguarded)`);
}

// ============================================================
// PERMISSION_MATRIX.md
// ============================================================
{
  const { catalogue, codes, roles } = facts.permissions;

  let out = HEADER(
    'Permission matrix',
    'Who may do what. A permission code is `module.resource.ACTION`, and every\n' +
    'decision is taken on the server: the client uses this catalogue only to decide\n' +
    'what to render, never whether to allow.',
  );

  out += `\n**${codes.length} permissions across ${catalogue.length} resources, granted through ${roles.length} roles.**\n`;

  out += '\n## Resources\n\n| Module | Resource | Label | Actions |\n| --- | --- | --- | --- |\n';
  for (const r of catalogue) {
    out += `| ${r.module} | ${r.resource} | ${r.label} | ${r.actions.join(', ')} |\n`;
  }

  out += '\n## Roles\n\n';
  for (const r of roles) {
    out += `### ${r.name} (\`${r.code}\`)\n\n${r.description}\n\n`;
    out += `Holds ${r.permissions.length} of ${codes.length} permissions.\n\n`;
    const byModule = new Map();
    for (const code of r.permissions) {
      const [mod] = code.split('.');
      if (!byModule.has(mod)) byModule.set(mod, []);
      byModule.get(mod).push(code.split('.').slice(1).join('.'));
    }
    for (const [mod, list] of [...byModule.entries()].sort()) {
      out += `- **${mod}**: ${list.sort().join(', ')}\n`;
    }
    out += '\n';
  }

  out += '## Coverage\n\n';
  out += 'Every permission and the roles that hold it. A permission held by nobody is\n';
  out += 'a feature nobody can reach, so the empty rows matter more than the full ones.\n\n';
  out += '| Permission | Held by |\n| --- | --- |\n';
  for (const code of codes) {
    const holders = roles.filter((r) => r.permissions.includes(code)).map((r) => r.code);
    out += `| \`${code}\` | ${holders.length ? holders.join(', ') : '**nobody**'} |\n`;
  }

  await writeFile(path.join(SPECS, 'PERMISSION_MATRIX.md'), out);
  console.log('PERMISSION_MATRIX.md');
}

// ============================================================
// MIGRATION_PLAN.md (the history is generated; the policy is prose)
// ============================================================
{
  const m = facts.migrations;
  let out = HEADER(
    'Migration plan',
    'How the schema moves forward without losing anything a pharmacy needs to keep.',
  );

  out += `
## The rule

Every schema change ships as a migration, applied with \`prisma migrate deploy\`.
Nothing is ever applied with \`db push\` outside a throwaway database, because
push resolves a difference by whatever route is convenient — including dropping
a column — and offers no record of what it did.

Migrations are generated non-interactively, because \`migrate dev\` needs a TTY
that a deployment pipeline does not have:

    npx prisma migrate diff \\
      --from-schema-datasource prisma/schema.prisma \\
      --to-schema-datamodel  prisma/schema.prisma \\
      --script > prisma/migrations/<timestamp>_<name>/migration.sql

## Adding a column to a populated table

A \`NOT NULL\` column with no default fails the moment the table has a row in it.
The order is always:

1. Add the column nullable, or with a default.
2. Backfill it.
3. Verify the backfill — count the rows that are still null.
4. Only then add the constraint.

This project has been bitten by exactly that once, on
\`warehouse_locations.updatedAt\`, which is why the check below runs over every
migration rather than living in somebody's memory.

## What is never done

- No migration drops a column holding data that has not been copied elsewhere.
- No migration resets users, passwords or sessions.
- No deployment reseeds a database that already holds real records: the seed
  refuses to run against a populated database.
- Permissions are the one thing that is *added* automatically on boot
  (\`PermissionSyncService\`), because a release that adds a resource would
  otherwise ship a feature nobody holds the permission to reach. It only ever
  adds. Nothing is revoked, so an administrator who narrowed a role, or a
  custom role somebody built, is left exactly as they left it.

## Applied migrations

${m.length} migrations, in order.

| # | Migration | Statements | Notes |
| --- | --- | --- | --- |
`;
  m.forEach((x, i) => {
    const notes = [
      x.destructive ? '**drops or renames — read before deploying**' : '',
      x.addsNotNullWithoutDefault ? '**adds NOT NULL with no default**' : '',
    ].filter(Boolean).join('; ') || 'additive';
    out += `| ${i + 1} | \`${x.label}\` | ${x.statements} | ${notes} |\n`;
  });

  const risky = m.filter((x) => x.destructive || x.addsNotNullWithoutDefault);
  out += `\n${risky.length === 0
    ? 'No migration in the history drops a column, renames a table, or adds a\n' +
      '`NOT NULL` column without a default. Every one is additive and can be applied\n' +
      'to a populated database without a backfill step.'
    : `${risky.length} migration(s) need reading before a deployment: ` +
      risky.map((x) => `\`${x.label}\``).join(', ') + '.'}\n`;

  await writeFile(path.join(SPECS, 'MIGRATION_PLAN.md'), out);
  console.log(`MIGRATION_PLAN.md (${risky.length} risky)`);
}

// ============================================================
// TEST_STRATEGY.md
// ============================================================
{
  const unitCases = facts.tests.reduce((s, t) => s + t.cases, 0);
  const e2eChecks = facts.e2e.reduce((s, t) => s + t.checks, 0);
  const integration = facts.tests.filter((t) => t.integration);

  let out = HEADER(
    'Test strategy',
    'What is tested, at which level, and why that level.',
  );

  out += `
## The three levels, and what each is for

**Pure unit tests** cover the arithmetic and the rules: FEFO ordering, expiry
bucketing, GS1 parsing, unit conversion, replenishment, the serial lifecycle
state machine, the scheduled-report window. These have no database because they
have no state — they are functions, and a function is easiest to trust when it
is tested as one.

**Integration tests** run against a real PostgreSQL. Anything that depends on a
transaction, a lock, or a constraint is tested here, because an in-memory
double proves nothing about \`SELECT ... FOR UPDATE\`. The ledger and the
accounting entries are the two that matter most: both are places where a
concurrency bug would corrupt data silently rather than throw.

**End-to-end suites** drive the running API over HTTP as real users, with real
tokens and real permissions. They are the only level that can catch a route
wired to the wrong path, a permission nobody holds, or a guard that lets a
cashier read the controlled register.

**Browser verification** drives the real web application in Chromium against the
real API. It is not a screenshot gallery: the pass or fail comes from
assertions — a page that scrolls sideways, text below the contrast floor, a
control with no accessible name, a request that failed, an exception on the
console. Screenshots are written so a person can look, not so a test can pass.

## What is never done

A test is not weakened to make an implementation pass, and a failing test is
never deleted because it revealed a bug. When a test and the code disagree, one
of them is wrong and the disagreement is the finding.

## Unit and integration suites

${facts.tests.length} suites, ${unitCases} cases. ${integration.length} of them require a database.

| Suite | Cases | Needs a database | Covers |
| --- | --- | --- | --- |
`;
  for (const t of facts.tests.sort((a, b) => a.file.localeCompare(b.file))) {
    out += `| \`${t.file}\` | ${t.cases} | ${t.integration ? 'yes' : 'no'} | ${t.suites.join('; ').replace(/\|/g, '\\|')} |\n`;
  }

  out += `\n## End-to-end suites\n\n${facts.e2e.length} suites, ${e2eChecks} checks, run against a seeded API on port 4000.\n\n`;
  out += '| Suite | Checks |\n| --- | --- |\n';
  for (const t of facts.e2e.sort((a, b) => a.file.localeCompare(b.file))) {
    out += `| \`scripts/${t.file}\` | ${t.checks} |\n`;
  }

  out += `
## Browser verification

\`scripts/ui-verify/verify.mjs\` (\`pnpm test:ui\`) drives ${facts.pages.length} pages.

The matrix is split by what each assertion actually depends on rather than run
as a full cross product. Contrast and accessible naming depend on the theme and
not on the width; overflow depends on the width and not on the theme. Running
all six widths in both themes repeated every finding twelve times, took long
enough to be skipped, and exhausted memory before finishing.

- Content checks: every page, both themes, at 1280px.
- Layout checks: every page, at 375, 428, 768, 1280, 1536 and 1920px.
- Keyboard: the skip link is the first tab stop, 25 consecutive tab stops all
  show a focus indicator, Ctrl+K opens the command palette and Escape closes it.

## Running everything

    pnpm test                  # unit and integration
    pnpm test:e2e*             # the seven end-to-end suites
    pnpm test:ui               # browser verification

The end-to-end suites share a login throttle. Running them back to back trips
it, which is the throttle working; leave about a minute between suites.
`;

  await writeFile(path.join(SPECS, 'TEST_STRATEGY.md'), out);
  console.log('TEST_STRATEGY.md');
}

console.log('\nGenerated documents written to specs/');
